# Generated by Django 5.2.9 on 2026-01-12 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_customuser_adresse_customuser_telephone_auditlog_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mouvementstock",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="mouvementstock",
            name="source",
            field=models.CharField(
                choices=[
                    ("manuel", "Manuel (interface)"),
                    ("vente", "Vente"),
                    ("transfert", "Transfert entrepôts"),
                    ("inventaire", "Inventaire"),
                    ("ajustement_auto", "Ajustement automatique"),
                    ("retour", "Retour client"),
                    ("autre", "Autre"),
                ],
                default="manuel",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="mouvementstock",
            name="transfert",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mouvements_stock",
                to="users.transfertentrepot",
            ),
        ),
        migrations.AddField(
            model_name="mouvementstock",
            name="vente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mouvements_stock",
                to="users.vente",
            ),
        ),
        migrations.AddIndex(
            model_name="mouvementstock",
            index=models.Index(
                fields=["produit", "entrepot"], name="users_mouve_produit_567181_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mouvementstock",
            index=models.Index(
                fields=["type_mouvement", "source"],
                name="users_mouve_type_mo_e17b76_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mouvementstock",
            index=models.Index(
                fields=["created_at"], name="users_mouve_created_d9cc04_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mouvementstock",
            index=models.Index(fields=["vente"], name="users_mouve_vente_i_db8ef0_idx"),
        ),
    ]
