# Generated by Django 5.2.9 on 2026-02-01 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_mouvementstock_options_mouvementstock_source_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="produit",
            name="prix_detail",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                help_text="Prix pour les ventes au détail",
                max_digits=10,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="produit",
            name="prix_gros",
            field=models.DecimalField(
                decimal_places=2,
                default=2,
                help_text="Prix pour les ventes en gros",
                max_digits=10,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="produit",
            name="prix_vente",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
