# Generated by Django 5.2.9 on 2026-02-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_produit_prix_detail_produit_prix_gros_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vente",
            name="type_vente",
            field=models.CharField(
                choices=[("gros", "Gros"), ("detail", "Détail")],
                default="detail",
                max_length=10,
            ),
        ),
    ]
