# Generated by Django 5.2.9 on 2026-02-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_vente_type_vente"),
    ]

    operations = [
        migrations.AddField(
            model_name="lignedevente",
            name="est_prix_gros",
            field=models.BooleanField(default=False),
        ),
    ]
