# Generated by Django 5.2.9 on 2026-02-01 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_lignedevente_est_prix_gros"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produit",
            name="prix_detail",
        ),
        migrations.RemoveField(
            model_name="produit",
            name="prix_gros",
        ),
        migrations.AddField(
            model_name="produit",
            name="prix_vente_detail",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="produit",
            name="prix_vente_gros",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
