# Generated by Django 5.2.9 on 2026-02-02 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_remove_produit_prix_detail_remove_produit_prix_gros_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="auditlog",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="lignedevente",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="lignetransfert",
            options={"ordering": ["id"]},
        ),
        migrations.AddField(
            model_name="lignedevente",
            name="montant_total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="vente",
            name="annule_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ventes_annulees",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="vente",
            name="confirmed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ventes_confirmees",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="vente",
            name="date_annulation",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vente",
            name="date_confirmation",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vente",
            name="montant_avant_remise",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="vente",
            name="montant_remise",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("creation", "Création"),
                    ("modification", "Modification"),
                    ("suppression", "Suppression"),
                    ("vente", "Vente"),
                    ("mouvement_stock", "Mouvement de stock"),
                    ("connexion", "Connexion"),
                    ("deconnexion", "Déconnexion"),
                    ("confirmation", "Confirmation"),
                    ("annulation", "Annulation"),
                    ("paiement", "Paiement"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["action", "created_at"], name="users_audit_action_9b343e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["modele", "objet_id"], name="users_audit_modele_cb1f76_idx"
            ),
        ),
    ]
