# Generated by Django 5.2.9 on 2026-02-06 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_alter_auditlog_options_alter_lignedevente_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vente",
            name="montant_avant_remise",
        ),
        migrations.AddField(
            model_name="vente",
            name="montant_avant_reduction",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="vente",
            name="montant_reduction",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="Montant de réduction appliqué",
            ),
        ),
        migrations.AddField(
            model_name="vente",
            name="type_reduction",
            field=models.CharField(
                choices=[
                    ("pourcentage", "Pourcentage"),
                    ("montant", "Montant fixe"),
                    ("aucune", "Aucune réduction"),
                ],
                default="aucune",
                max_length=20,
                verbose_name="Type de réduction",
            ),
        ),
        migrations.AddField(
            model_name="vente",
            name="valeur_reduction",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Valeur de réduction",
            ),
        ),
    ]
