# Generated by Django 5.2.9 on 2026-02-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_remove_vente_montant_avant_remise_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="numero_client",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
