# Generated by Django 5.2.9 on 2026-02-26 20:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_client_numero_client"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lignedevente",
            options={"ordering": ["created_at"]},
        ),
        migrations.AlterModelOptions(
            name="lignetransfert",
            options={},
        ),
        migrations.AlterModelOptions(
            name="transfertentrepot",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveIndex(
            model_name="auditlog",
            name="users_audit_action_9b343e_idx",
        ),
        migrations.RemoveIndex(
            model_name="auditlog",
            name="users_audit_modele_cb1f76_idx",
        ),
        migrations.RemoveField(
            model_name="lignedevente",
            name="stock_preleve",
        ),
        migrations.RemoveField(
            model_name="transfertentrepot",
            name="confirme_at",
        ),
        migrations.AddField(
            model_name="lignedevente",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transfertentrepot",
            name="confirme_le",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transfertentrepot",
            name="confirme_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transferts_confirme",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="modele",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="lignedevente",
            name="montant_total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="lignedevente",
            name="quantite",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="lignetransfert",
            name="quantite",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="mouvementstock",
            name="quantite",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="produit",
            name="stock_alerte",
            field=models.DecimalField(decimal_places=2, default=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name="stockentrepot",
            name="quantite",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="stockentrepot",
            name="quantite_reservee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="stockentrepot",
            name="stock_alerte",
            field=models.DecimalField(decimal_places=2, default=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name="transfertentrepot",
            name="entrepot_destination",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transferts_destination",
                to="users.entrepot",
            ),
        ),
        migrations.AlterField(
            model_name="transfertentrepot",
            name="entrepot_source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transferts_source",
                to="users.entrepot",
            ),
        ),
        migrations.AlterField(
            model_name="transfertentrepot",
            name="motif",
            field=models.TextField(),
        ),
        migrations.AlterUniqueTogether(
            name="lignetransfert",
            unique_together={("transfert", "produit")},
        ),
    ]
