# Generated by Django 5.2.9 on 2026-02-26 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_alter_lignedevente_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lignedevente",
            options={"verbose_name_plural": "Lignes de vente"},
        ),
        migrations.AlterModelOptions(
            name="transfertentrepot",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="lignetransfert",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="lignedevente",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="transfertentrepot",
            name="confirme_le",
        ),
        migrations.RemoveField(
            model_name="transfertentrepot",
            name="confirme_par",
        ),
        migrations.AddField(
            model_name="transfertentrepot",
            name="date_confirmation",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transfertentrepot",
            name="date_reception",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="details",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="objet_id",
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="lignedevente",
            name="quantite",
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
        migrations.AlterField(
            model_name="lignetransfert",
            name="quantite",
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
        migrations.AlterField(
            model_name="mouvementstock",
            name="quantite",
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
        migrations.AlterField(
            model_name="produit",
            name="stock_alerte",
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name="stockentrepot",
            name="quantite",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="stockentrepot",
            name="quantite_reservee",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="stockentrepot",
            name="stock_alerte",
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name="transfertentrepot",
            name="entrepot_destination",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transferts_entrants",
                to="users.entrepot",
            ),
        ),
        migrations.AlterField(
            model_name="transfertentrepot",
            name="entrepot_source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transferts_sortants",
                to="users.entrepot",
            ),
        ),
        migrations.AlterField(
            model_name="transfertentrepot",
            name="motif",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="transfertentrepot",
            name="statut",
            field=models.CharField(
                choices=[
                    ("brouillon", "Brouillon"),
                    ("confirme", "Confirmé"),
                    ("en_cours", "En cours"),
                    ("termine", "Terminé"),
                    ("annule", "Annulé"),
                ],
                default="brouillon",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["user", "modele"], name="users_audit_user_id_25f652_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["created_at"], name="users_audit_created_6518da_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lignedevente",
            index=models.Index(
                fields=["vente", "produit"], name="users_ligne_vente_i_9cd7de_idx"
            ),
        ),
    ]
