# Generated by Django 5.2.9 on 2026-02-26 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_alter_lignedevente_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lignedevente",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="lignetransfert",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="transfertentrepot",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="lignetransfert",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="lignedevente",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="transfertentrepot",
            name="confirme_le",
        ),
        migrations.RemoveField(
            model_name="transfertentrepot",
            name="confirme_par",
        ),
        migrations.AddField(
            model_name="lignedevente",
            name="stock_preleve",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="transfertentrepot",
            name="confirme_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("creation", "Création"),
                    ("modification", "Modification"),
                    ("suppression", "Suppression"),
                    ("vente", "Vente"),
                    ("mouvement_stock", "Mouvement de stock"),
                    ("connexion", "Connexion"),
                    ("deconnexion", "Déconnexion"),
                    ("confirmation", "Confirmation"),
                    ("annulation", "Annulation"),
                    ("paiement", "Paiement"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="modele",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="lignedevente",
            name="montant_total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="transfertentrepot",
            name="entrepot_destination",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transferts_entrants",
                to="users.entrepot",
            ),
        ),
        migrations.AlterField(
            model_name="transfertentrepot",
            name="entrepot_source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transferts_sortants",
                to="users.entrepot",
            ),
        ),
        migrations.AlterField(
            model_name="transfertentrepot",
            name="motif",
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["action", "created_at"], name="users_audit_action_9b343e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["modele", "objet_id"], name="users_audit_modele_cb1f76_idx"
            ),
        ),
    ]
